server:
  port: 8010                                      # 此Consumer Process啟動的port
spring:
  application:
    name: user-consumer                           # 指定要注冊到Eureka Server上的應用程式之名稱
eureka:
  client:
    serviceUrl:                                   # http://localhost:8761/eureka/,表示用戶或微服務要與Eureka Server溝通的地址,默認即為左顯示,若有多個Eureka Server地址可以用逗號隔開
      defaultZone: http://leoliu:mypass@peer1:8761/eureka/,http://leoliu:mypass@peer2:8762/eureka/,http://leoliu:mypass@peer3:8763/eureka/  # 若Eureka Server有設定基本認證時,需加上"帳號:密碼"的格式
  instance:
    prefer-ip-address: true                       # 是否把自己的ip註冊到Eureka Server上,若為false表示會註冊此微服務所在電腦的hostname到Eureka Server上
    metadata-map:                                 # 可以自己定義此instance的metadata,使用key/value的型式
      my-metadata1: test consumer metadata 1
      my-metadata2: test consumer metadata 2
logging:
  level:
    com.itmuch.cloud.study.user.feign.UserFeignClient: DEBUG # 把Feign Client接口的logging級別設為DEBUG，因為Feign的Logger Level只能對DEBUG模式有用
feign:
  hystrix:
    enabled: true  #把Feign的Hystrix功能打開,即每個Feign Client的接口都會具備容錯機制(超時,切斷,恢復,隔離...等等)