server:
  port: 8888                                      # 此Config Server Process啟動的port
spring:
  application:
     name: configserver
  profiles:
     active: native                                   # 本地檔案,無GIT
  cloud:
    config:
      server:
        native:
          search-locations: file:D:/CloudProperty     #本地檔案,無GIT,直接指定一個你想存放各個微服務之property檔的位置
eureka:
  client:
    serviceUrl:                         # http://localhost:8761/eureka/,表示用戶或微服務要與Eureka Server溝通的地址,默認即為左顯示,若有多個Eureka Server地址可以用逗號隔開
      defaultZone: http://leoliu:mypass@peer1:8761/eureka/,http://leoliu:mypass@peer2:8762/eureka/,http://leoliu:mypass@peer3:8763/eureka/  # 若Eureka Server有設定基本認證時,需加上"帳號:密碼"的格式
  instance:
    prefer-ip-address: true             # 是否把自己的ip註冊到Eureka Server上,若為false表示會註冊此微服務所在電腦的hostname到Eureka Server上
    metadata-map:                       # 可以自己定義此instance的metadata,使用key/value的型式
      my-metadata1: test config server metadata 1
      my-metadata2: test config server metadata 2
management:
  security:
    enabled: false                                    # 把安全性關掉,這裡是方便測試