spring:
  application:
     name: myconfigserver
  profiles:
     active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:D:/MyWork/test1,file:D:/MyWork/test2